
/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f877.h>
//#include <stdio.h>

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word at 0x2007 CONFIG = _XT_OSC & _WDT_OFF & _PWRTE_OFF & _BODEN_ON & _LVP_ON & _CPD_OFF & _WRT_ENABLE_ON & _DEBUG_ON & _CP_OFF;

void delay(unsigned count) {
    while (count--)  {
        continue;
    }
}

void serial_setup_19200() {

    // Configure UART serial transmit
    SPBRG = 12; // 4MHz = > 19200 baud
    BRGH  = 1;
    SYNC  = 0;
    SPEN  = 1;
    TXIE  = 1;

    // enable transmission
    TXEN = 1;
    GIE  = 1;
    PEIE = 1;
}

#define RING_SZ (16)
char txring[RING_SZ];
unsigned char txring_in  = 0;
unsigned char txring_out = 0;

void intr() interrupt 0 {
    if(TXIF) { // serial interrupt
        if( txring_out != txring_in ) {
            txring_out = (txring_out + 1) & (RING_SZ-1);
            TXREG = txring[txring_out];
        }
    } 
}

void print(char* p) {
    unsigned char c;
    while(c = *p) {
        unsigned char txring_next = (txring_in + 1) & (RING_SZ-1);
        if (txring_next != txring_out) {
            txring[txring_next] = c;
            txring_in = txring_next;
            intr(); // call here to prime if empty tx buffer
            p++;
        }
    }
}

// ----------------------------------------------------------------------------
void main(void) {
    TRISB = 0;
    serial_setup_19200();
    while (1) {
        print("Hello World\n");
        delay(1000);
/* #include <usart.h> */
    }
}
