
/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f877.h>
#include <stdio.h>
/* #include <usart.h> */

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word at 0x2007 CONFIG = _XT_OSC & _WDT_OFF & _PWRTE_OFF & _BODEN_ON & _LVP_ON & _CPD_OFF & _WRT_ENABLE_ON & _DEBUG_ON & _CP_OFF;

/* void isr() interrupt 0 { */
/*     /1* interrupt service routine *1/ */
/*     /1* << insert interrupt code >> *1/ */
/* } */

void delay();

void delay() {
    int counter = 0;
    for (counter = 0; counter<1000; counter++) {
        ;
    }
}

void serial_setup_19200() {

    // Configure UART serial transmit

    SPBRG = 12; // 4MHz = > 19200 baud
    BRGH  = 1;
    SYNC  = 0;
    SPEN  = 1;
    TXIE  = 1;

    // enable transmission
    TXEN  = 1;
    TXREG = 'n'; // Actually emit our char.
}

void timer_intr() interrupt 0 {
    if(TXIF) { // serial interrupt
        // Most interrupts must be cleared in software:
        // TXIF = 0; // not doable :)
        TXREG = 'n';
        TXIE = 0;
    } 
}

/* The next step is to write a print string command. The idea is to have a small, circular, 
 * buffer of say 16 bytes which you can add chars to be output. To start with, I'm treating 
 * the output buffer as a once off buffer. */
char ring[16];
unsigned char ring_pointer = 0;

void print(char* p) {
    unsigned char i = 0;
    unsigned char c;
    //while(TXIE); // wait for interrupts to finish last message.
    // May as well start transmitting first char.
    while(c = *p) {
        ring[i] = c;
        i++;
        p++;
    }
    ring[i]      = 0; // terminate
    ring_pointer = 0;
    c            = ring[0];
    if(c) {
        ring_pointer++; // Only move forward if there is a char there
        TXIE = 1;
        TXREG = c;
    }
}

void main(void) {
    /* serial_setup_19200(); */
    TRISB = 0;
    while (1) {
        PORTB = 0x0F;

        delay();

        PORTB = 0x00;

        delay();
        /* print("Hello World\n"); */
    }
}
